### ISSUE TITLE
Location names are appearing incorrectly in list.

### ISSUE THREAD

**Issue by Pragyad07** [hotwax/inventory-count#127]
## Current behavior
On the count page of the product, the location's name in the list of a particular facility is not appearing correctly.
![Screenshot 2022-12-14 at 11 06 28 AM](https://user-images.githubusercontent.com/64180958/207516234-20dec152-009d-42ad-9a30-91122ca3f246.png)

## Expected behavior
On the count page of the product, the stock count of items is updated and then the name of locations in the list should appear as their actual name i.e in an instance.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by shashwatbangar** [comment]
Earlier we were showing locationPath in the list which was combination of..
areaId + aisleId + sectionId + levelId + positionId & because this was all coming null from API, 0 was getting shown in the list. Now changed it to locationSeqId and working fine.

**Also scrolling does not work in the list**
