### ISSUE TITLE
Show spinner while searching product

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#349]
## What is the motivation for adding/enhancing this feature?

Need to show spinner while searching product so user knows that system is doing something on create count screen.

**Comment by ymaheshwari1** [comment]
We already have a spinner added when searching for a product, but it might not be visible due to api returning results quickly.
Also we have a 1 sec delay setup on api call, so that the api calls are only made when user does not type anything in the 1 sec duration. This is done so that minimum api calls are made as when user is typing fast.

**Comment by dt2patel** [comment]
In this case, can we start the spinner even when the delay is active?

**Comment by ymaheshwari1** [comment]
> second

Will add this support.

**Comment by Adameddy26** [comment]
Verified and working fine in DEV environment of App version INVENTORY-COUNT-2.0-BEE32C4
Hence, closing this issue.
